name: GitHub Deployments
description: GitHub action for working painlessly with deployment statuses.
author: bobheadxi
branding:
  icon: bookmark
  color: yellow
runs:
  using: node12
  main: lib/main.js

inputs:
  token:
    required: true
    description: GitHub token
  step:
    required: true
    description: One of 'start' and 'finish'
  env:
    required: false
    description: The name of the environment being deployed to
  auto_inactive:
    required: false
    description: Set auto_inactive (see https://developer.github.com/v3/repos/deployments/#inactive-deployments)
  logs:
    required: false
    description: URL to logs
  desc:
    required: false
    description: Description to set in status
  ref:
    required: false
    description: The git ref to use for the deploy, defaults to github.ref
  payload:
    required: false
    description: A JSON-formatted string to be parsed and sent in the webhook body
